language: c
compiler: gcc
env:
    global:
        - FC=gfortran-4.9
install:
    # we do this because pfunit compilation fails with gfortran 4.6
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 gfortran-4.9
  - sudo pip install cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./pftest_alltests
after_success:
  - coveralls --root .. --extension .F90 -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"
