language: fortran
install:
    # we do this because pfunit compilation fails with gfortran 4.6
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gfortran-4.8
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./pftest_alltests
after_success:
  - coveralls --root ..
