sudo: false

language: c

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gfortran-4.9
      - python-virtualenv
      - cmake
      - cmake-data

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew outdated xctool || brew upgrade xctool
      brew unlink gcc
      brew install python gcc cmake
      brew linkapps python
    fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      virtualenv venv
      source venv/bin/activate
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install -r requirements.txt

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - if test ${TRAVIS_OS_NAME} = linux; then FC=gfortran-4.9 cmake ..;
                                       else FC=gfortran     cmake ..; fi
  - make
  - ./pftest_alltests

after_success:
  - if test ${TRAVIS_OS_NAME} = linux; then coveralls --gcov /usr/bin/gcov-4.9 --root .. --extension .F90 -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"; fi

notifications:
  email: false
